SELECT * FROM tbProduto WHERE PRODUTO = '544931';

SELECT * FROM tbCliente WHERE CIDADE = 'Rio de Janeiro';

SELECT * FROM tbProduto WHERE SABOR = 'Limão';

SELECT * FROM tbProduto WHERE SABOR = 'Cítricos';

UPDATE tbProduto SET SABOR = 'Cítricos' WHERE SABOR = 'Limão';


SELECT * FROM tbCliente;

SELECT * FROM tbCliente WHERE IDADE = 22;

SELECT * FROM tbCliente WHERE IDADE > 22;

SELECT * FROM tbCliente WHERE IDADE < 22;

SELECT * FROM tbCliente WHERE IDADE != 22;
SELECT * FROM tbCliente WHERE IDADE <> 22;

SELECT * FROM tbCliente WHERE NOME > 'Fernando Cavalcante';

SELECT * FROM tbProduto WHERE PRECO_LISTA = 16.008;

SELECT * FROM tbProduto WHERE PRECO_LISTA > 16.008;

SELECT * FROM tbProduto WHERE PRECO_LISTA < 16.008;

SELECT * FROM tbProduto WHERE PRECO_LISTA <> 16.008;

SELECT * FROM tbProduto WHERE PRECO_LISTA BETWEEN 16.007 AND 16.009;

SELECT * FROM tbCliente WHERE DATA_NASCIMENTO = '1995-01-13';

SELECT * FROM tbCliente WHERE DATA_NASCIMENTO > '1995-01-13';

SELECT * FROM tbCliente WHERE DATA_NASCIMENTO < '1995-01-13';

SELECT * FROM tbCliente WHERE DATA_NASCIMENTO = '1995-01-13';

SELECT * FROM tbCliente WHERE YEAR(DATA_NASCIMENTO) = 1995;

SELECT * FROM tbCliente WHERE MONTH(DATA_NASCIMENTO) = 10;

SELECT * FROM tbProduto WHERE PRECO_LISTA >= 16.007 AND PRECO_LISTA <= 16.009;

SELECT * FROM tbCliente WHERE IDADE >= 18 AND IDADE <= 22 AND SEXO = 'M';

SELECT * FROM tbCliente WHERE CIDADE = 'Rio dew Janeiro' OR BAIRRO = 'Jardins';

SELECT * FROM tbCliente WHERE (IDADE >= 18 AND IDADE <= 22 AND SEXO = 'M') OR (CIDADE = 'Rio dew Janeiro' OR BAIRRO = 'Jardins');


















