SELECT NOME, MATRICULA FROM TABELA_DE_VENDEDORES;

SELECT * FROM TABELA_DE_VENDEDORES WHERE NOME = 'Cláudia Morais';

SELECT * FROM TABELA_DE_VENDEDORES WHERE PERCENTUAL_COMISSAO > 0.10;

SELECT * FROM TABELA_DE_VENDEDORES WHERE YEAR(DATA_ADMISSAO) >= 2016;

SELECT * FROM TABELA_DE_VENDEDORES WHERE DE_FERIAS = 1 AND YEAR(DATA_ADMISSAO) < 2016;

