USE SUCOS;

ALTER TABLE tbProduto ADD PRIMARY KEY (PRODUTO);

SELECT * FROM tbProduto; 

INSERT INTO tbProduto (
PRODUTO,  NOME, EMBALAGEM, TAMANHO, SABOR,
PRECO_LISTA) VALUES
('544931', 'Frescor do Verão - 350 ml - Limão', 'PET', '350 ml','Limão',3.20);

UPDATE tbProduto SET EMBALAGEM = 'Lata', PRECO_LISTA = 2.46
WHERE PRODUTO = '544931';